
package javase.jaxws.metro.example2.stub;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service1Soap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/sayHello")
    @WebResult(name = "sayHelloResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://tempuri.org/", className = "javase.jaxws.metro.example2.stub.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://tempuri.org/", className = "javase.jaxws.metro.example2.stub.SayHelloResponse")
    public String sayHello();

}
